<?php
session_start();
require_once 'config/db.php';

if (!isset($_SESSION['user_id'])) { die("Access Denied"); }

$program_id = isset($_GET['program_id']) ? intval($_GET['program_id']) : 0;
$area_id = isset($_GET['area_id']) ? intval($_GET['area_id']) : 0;

// Fetch Program & Area Info
$p_res = $conn->query("SELECT program_name, program_code FROM programs WHERE program_id = $program_id");
$program = $p_res->fetch_assoc();

$a_res = $conn->query("SELECT area_no, area_title FROM areas WHERE area_id = $area_id");
$area = $a_res->fetch_assoc();

// Determine which type of report to generate
$type = isset($_GET['type']) ? $_GET['type'] : 'internal';
if ($type !== 'internal' && $type !== 'external') {
    $type = 'internal'; // Sanitize to a safe default
}

// Fetch Ratings
$ratings = [];
$average = 0;

$sql = "SELECT sr.rating, sp.parameter_text, sp.parameter_order 
        FROM survey_ratings sr
        JOIN survey_parameters sp ON sr.parameter_index = sp.param_id
        WHERE sr.program_id = ? AND sr.area_id = ? AND sr.accreditor_type = ?
        ORDER BY sp.parameter_order ASC";

$stmt = $conn->prepare($sql);
if ($stmt) {
    $stmt->bind_param("iis", $program_id, $area_id, $type);
    $stmt->execute();
    $r_res = $stmt->get_result();
    if ($r_res) {
        $total_score = 0;
        $count = 0;
        while($r = $r_res->fetch_assoc()) {
            $ratings[] = $r;
            $total_score += $r['rating'];
            $count++;
        }
        $average = $count > 0 ? number_format($total_score / $count, 2) : 0;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Survey Result - <?= htmlspecialchars($program['program_code']) ?></title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #4f46e5; margin-bottom: 5px; }
        .sub-header { font-size: 14px; color: #666; }
        .meta { margin-bottom: 30px; background: #f9fafb; padding: 20px; border-radius: 8px; }
        .meta-row { display: flex; justify-content: space-between; margin-bottom: 10px; }
        .label { font-weight: bold; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th, td { padding: 12px 15px; border-bottom: 1px solid #ddd; text-align: left; }
        th { background-color: #f3f4f6; font-weight: 600; }
        .rating-cell { font-weight: bold; text-align: center; }
        .score-box { text-align: right; font-size: 18px; font-weight: bold; margin-top: 20px; }
        .score-val { color: #4f46e5; font-size: 24px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
        
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body onload="window.print()">

    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #4f46e5; color: white; border: none; border-radius: 5px; cursor: pointer;">Download / Print PDF</button>
    </div>

    <div class="header">
        <div class="logo">BISU AACCUP Accreditation</div>
        <div class="sub-header">Official <?= ucfirst($type) ?> Self-Survey Assessment Result</div>
    </div>
    <div class="meta">
        <div class="meta-row">
            <span class="label">Program:</span>
            <span><?= htmlspecialchars($program['program_name']) ?> (<?= htmlspecialchars($program['program_code']) ?>)</span>
        </div>
        <div class="meta-row">
            <span class="label">Area Evaluated:</span>
            <span>Area <?= htmlspecialchars($area['area_no']) ?>: <?= htmlspecialchars($area['area_title']) ?></span>
        </div>
        <div class="meta-row">
            <span class="label">Date Generated:</span>
            <span><?= date('F d, Y') ?></span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 70%;">Parameter / Criteria</th>
                <th style="width: 30%; text-align: center;">Rating (1-5)</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($ratings as $r): ?>
            <tr>
                <td><?= htmlspecialchars($r['parameter_text']) ?></td>
                <td class="rating-cell"><?= htmlspecialchars($r['rating']) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="score-box">
        Average Score: <span class="score-val"><?= $average ?></span> / 5.00
    </div>

    <div class="footer">
        Generated by BISU AACCUP System &bull; This document is for accreditation purposes only.
    </div>

</body>
</html>